DA2.Web/DA2.Web/Controllers/DanhMucController.cs
using DA2.Data.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace DA2.Web.Controllers
{
    public class DanhMucController : Controller
    {
        private UnitOfWork _uow = new UnitOfWork();
        private static string alias { get; set; }
        public ActionResult Index(string alias)
        {
            ViewBag.alias = alias;
            DanhMucController.alias = alias;
            return View();
        }

        public PartialViewResult GetPaging(int? page)
        {
            var list = _uow.ProductRepository.GetAll().Where(x => x.BRAND.alias.Equals(DanhMucController.alias)).Where(x => x.deleted == false).OrderBy(x => x.created);
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            if (list.ToList().Count == 0)
                return PartialView("_404");
            else
                return PartialView("_PartialViewDMSP", list.ToPagedList(pageNumber, pageSize));
        }
    }
}

DA2.Web/DA2.Web/Controllers/SanPhamController.cs
using DA2.Data.Infrastructure;
using DA2.Data.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DA2.Web.Controllers
{
    public class SanPhamController : Controller
    {
        private UnitOfWork _uow = new UnitOfWork();
        public ActionResult Index(string aliasSP)
        {
            PRODUCT sp = _uow.ProductRepository.Get(x => x.alias.Equals(aliasSP)).Where(x => x.deleted == false).SingleOrDefault();
            ViewBag.Random = _uow.ProductRepository.GetAll().Where(x => x.deleted == false).Take(10);
            return View(sp);
        }
    }
}

DA2.Web/DA2.Web/Views/DanhMuc/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<DA2.Data.Model.PRODUCT>
@{
    ViewBag.Title = "Danh mục " + @ViewBag.alias;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="category-grid">
    <div class="container">

        <!-- ========================================= SIDEBAR ========================================= -->
        <div class="col-xs-12 col-sm-3 no-margin sidebar narrow">
            <!-- ========================================= PRODUCT FILTER ========================================= -->
            <div class="widget">
                <h1>Product Filters</h1>
                <div class="body bordered">

                    <div class="category-filter">
                        <h2>Brands</h2>
                        <hr>
                        <ul>
                            <li><input checked="checked" class="le-checkbox" type="checkbox" /> <label>Samsung</label> <span class="pull-right">(2)</span></li>
                            <li><input class="le-checkbox" type="checkbox" /> <label>Dell</label> <span class="pull-right">(8)</span></li>
                            <li><input class="le-checkbox" type="checkbox" /> <label>Toshiba</label> <span class="pull-right">(1)</span></li>
                            <li><input class="le-checkbox" type="checkbox" /> <label>Apple</label> <span class="pull-right">(5)</span></li>
                        </ul>
                    </div><!-- /.category-filter -->

                    <div class="price-filter">
                        <h2>Price</h2>
                        <hr>
                        <div class="price-range-holder">
                            <input type="text" class="price-slider" value="">
                            <span class="min-max">
                                Price: $89 - $2899
                            </span>
                            <span class="filter-button">
                                <a href="#">Filter</a>
                            </span>
                        </div>
                    </div><!-- /.price-filter -->
                </div><!-- /.body -->
            </div><!-- /.widget -->
            <!-- ========================================= PRODUCT FILTER : END ========================================= -->
            <div class="widget">
                <h1 class="border">Sản phẩm khác</h1>
                <ul class="product-list">
                    <li>
                        <div class="row">
                            <div class="col-xs-4 col-sm-4 no-margin">
                                <a href="#" class="thumb-holder">
                                    <img alt="" src="assets/images/blank.gif" data-echo="assets/images/products/product-small-01.jpg" />
                                </a>
                            </div>
                            <div class="col-xs-8 col-sm-8 no-margin">
                                <a href="#">Netbook Acer </a>
                                <div class="price">
                                    <div class="price-prev">$2000</div>
                                    <div class="price-current">$1873</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="row">
                            <div class="col-xs-4 col-sm-4 no-margin">
                                <a href="#" class="thumb-holder">
                                    <img alt="" src="assets/images/blank.gif" data-echo="assets/images/products/product-small-02.jpg" />
                                </a>
                            </div>
                            <div class="col-xs-8 col-sm-8 no-margin">
                                <a href="#">PowerShot Elph 115 16MP Digital Camera</a>
                                <div class="price">
                                    <div class="price-prev">$2000</div>
                                    <div class="price-current">$1873</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="row">
                            <div class="col-xs-4 col-sm-4 no-margin">
                                <a href="#" class="thumb-holder">
                                    <img alt="" src="assets/images/blank.gif" data-echo="assets/images/products/product-small-03.jpg" />
                                </a>
                            </div>
                            <div class="col-xs-8 col-sm-8 no-margin">
                                <a href="#">PowerShot Elph 115 16MP Digital Camera</a>
                                <div class="price">
                                    <div class="price-prev">$2000</div>
                                    <div class="price-current">$1873</div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="row">
                            <div class="col-xs-4 col-sm-4 no-margin">
                                <a href="#" class="thumb-holder">
                                    <img alt="" src="assets/images/blank.gif" data-echo="assets/images/products/product-small-01.jpg" />
                                </a>
                            </div>
                            <div class="col-xs-8 col-sm-8 no-margin">
                                <a href="#">Netbook Acer</a>
                                <div class="price">
                                    <div class="price-prev">$2000</div>
                                    <div class="price-current">$1873</div>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li>
                        <div class="row">
                            <div class="col-xs-4 col-sm-4 no-margin">
                                <a href="#" class="thumb-holder">
                                    <img alt="" src="assets/images/blank.gif" data-echo="assets/images/products/product-small-02.jpg" />
                                </a>
                            </div>
                            <div class="col-xs-8 col-sm-8 no-margin">
                                <a href="#">PowerShot Elph 115 16MP Digital Camera</a>
                                <div class="price">
                                    <div class="price-prev">$2000</div>
                                    <div class="price-current">$1873</div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div><!-- /.widget -->
            <div class="widget">
                <div class="simple-banner">
                    <a href="#"><img alt="" class="img-responsive" src="assets/images/blank.gif" data-echo="assets/images/banner/banner-simple.jpg" /></a>
                </div>
            </div>
        </div>
        <!-- ========================================= SIDEBAR : END ========================================= -->
        <!-- ========================================= CONTENT ========================================= -->
        <div class="col-xs-12 col-sm-9 no-margin wide sidebar">
            <section id="gaming">
                <div class="grid-list-products">
                    <h3 class="section-title">Danh mục @ViewBag.alias</h3>
                    @{Html.RenderAction("GetPaging", "DanhMuc", new { page = 1 });}
                </div><!-- /.grid-list-products -->
            </section><!-- /#gaming -->
        </div><!-- /.col -->
                <!-- ========================================= CONTENT : END ========================================= -->
        </div><!-- /.container -->
</section><!-- /#category-grid -->

DA2.Web/DA2.Web/Views/DanhMuc/_404.cshtml
<hr/>
<h3 class="text-danger">Không tìm thấy sản phẩm nào!</h3>

DA2.Web/DA2.Web/Views/DanhMuc/_PartialViewDMSP.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<DA2.Data.Model.PRODUCT>

<div class="tab-content">
    <div id="grid-view" class="products-grid fade tab-pane in active">

        <div class="product-grid-holder">
            <div class="row no-margin">
                @foreach (var item in Model)
                {
                    <div class="col-xs-12 col-sm-4 no-margin product-item-holder hover">
                        <div class="product-item">
                            <div class="ribbon red"><span>HOT!</span></div>
                            <a href="@Url.Action("Index", "SanPham", new { @aliasSP = item.alias })">
                                <div class="image">
                                    <img alt="" src="~/assets/client/image1/ajax.gif" data-echo="/ProductImages/@item.image" />
                                </div>
                            </a>
                            <div class="body">
                                <div class="title">
                                    <a href="@Url.Action("Index", "SanPham", new { @aliasSP = item.alias })">@item.name</a>
                                </div>
                                <div class="brand">@item.BRAND.name</div>
                            </div>
                            <div class="prices">
                                <div class="price-current text-center">@item.price.GetValueOrDefault().ToString("N0")đ</div>
                            </div>
                            <div class="hover-area">
                                <div class="add-cart-button">
                                    @if (item.stock == 0)
                                    {

                                        <a href="#" class="le-button btn-het-hang">Tạm hết hàng</a>
                                    }
                                    else
                                    {
                                        <a href="/them-gio-hang?productId=@item.id&quantity=1" class="le-button">Thêm Giỏ Hàng</a>
                                    }
                                </div>
                            </div>
                        </div><!-- /.product-item -->
                    </div><!-- /.product-item-holder -->
                }

            </div><!-- /.row -->
        </div><!-- /.product-grid-holder -->
        <div class="pagination-holder">
            <div class="row">
                <div class="col-xs-12 col-sm-6 text-left">
                    <ul class="pagination ">
                        @Html.PagedListPager(Model, page => Url.Action("GetPaging", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "gaming" }))
                    </ul>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="result-counter">
                        Trang <span>@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)</span> / <span>@Model.PageCount</span>
                    </div><!-- /.result-counter -->
                </div>
            </div><!-- /.row -->
        </div><!-- /.pagination-holder -->
    </div><!-- /.products-grid #grid-view -->
</div><!-- /.tab-content -->