DA2.Web/DA2.Web/Controllers/TaiKhoanController.cs
using DA2.Data.Infrastructure;
using DA2.Data.Model;
using DA2.Web.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DA2.Web.Controllers
{
    public class TaiKhoanController : Controller
    {
        private UnitOfWork _uow = new UnitOfWork();
        // GET: TaiKhoan
        public ActionResult Index()
        {
            if (Session[CommonConstant.CustomerSession] == null)
            {
                return Redirect("/Auth");
            }
            var cusId = ((CustomerLoginInfo)Session[CommonConstant.CustomerSession]).id;
            var cusInfo = _uow.CustomerRepository.GetById(cusId);
            return View(cusInfo);
        }

        [HttpPost]
        public ActionResult Index(CUSTOMER cus)
        {
            if(ModelState.IsValid)
            {
                var updateCus = _uow.CustomerRepository.GetById(cus.id);
                updateCus.name = cus.name;
                updateCus.tel = cus.tel;
                updateCus.address = cus.address;
                updateCus.password = updateCus.password;
                _uow.CustomerRepository.Update(updateCus);
                _uow.Save();
                ViewBag.Success = "Cập nhật thông tin thành công!";
            }
            return View("Index");
        }

        public ActionResult LichSuDatHang()
        {
            if (Session[CommonConstant.CustomerSession] == null)
            {
                return Redirect("/Auth");
            }
            var cusId = ((CustomerLoginInfo)Session[CommonConstant.CustomerSession]).id;
            var cusBill = _uow.BillRepository.GetAll().Where(x => x.customer_id == cusId);
            return View(cusBill);
        }

        public PartialViewResult XemDonHang(int id)
        {
            var billitem = _uow.BillItemRepository.GetAll().Where(x => x.bill_id == id);
            ViewBag.id = id;
            ViewBag.bill = _uow.BillRepository.GetById(id);
            return PartialView("XemDonHang", billitem);
        }

        [HttpGet]
        public ActionResult DoiMatKhau()
        {
            return View();

        }
        
    }
}

DA2.Web/DA2.Web/Views/TaiKhoan/DoiMatKhau.cshtml
@model DA2.Data.Model.CUSTOMER
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main id="blog" class="inner-bottom-xs">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <aside class="sidebar blog-sidebar">
                    <div class="widget">
                        <h4>Tài khoản của tôi <i class="fa fa-child" aria-hidden="true"></i></h4>
                        <div class="body">
                            <ul class="le-links">
                                <li><a href="/TaiKhoan">Cập nhật tài khoản</a></li>
                                <li class="tk-active"><a href="/TaiKhoan/DoiMatKhau">Mật khẩu</a></li>
                                <li><a href="/TaiKhoan/LichSuDatHang">Lịch sử đặt hàng</a></li>
                            </ul><!-- /.le-links -->
                        </div>
                    </div><!-- /.widget -->
                </aside><!-- /.sidebar .blog-sidebar -->
            </div><!-- /.col -->

            <div class="col-md-9">
                Đang cập nhật...
                @*<section class="section register inner-left-xs">
                    <h4 class="text-success">@ViewBag.Success</h4>
                    <br />
                    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "cf-style-1" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)
                        @Html.HiddenFor(model => model.email)
                        @Html.HiddenFor(model => model.password)

                        <div class="field-row">
                            @Html.LabelFor(model => model.email)
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "le-input", @disabled = "true" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="field-row">
                            <label>Họ và tên</label>
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "le-input" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="field-row">
                            <label>Số điện thoại</label>
                            @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "le-input" } })
                            @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="field-row">
                            <label>Địa chỉ</label>
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "le-input" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="buttons-holder">
                            <button type="submit" class="le-button huge">Cập nhật</button>
                        </div><!-- /.buttons-holder -->
                    }
                </section><!-- /.register -->*@
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</main><!-- /.inner-bottom-xs -->

DA2.Web/DA2.Web/Views/TaiKhoan/Index.cshtml
@model DA2.Data.Model.CUSTOMER
@{
    ViewBag.Title = "Tài khoản của tôi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main id="blog" class="inner-bottom-xs">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <aside class="sidebar blog-sidebar">
                    <div class="widget">
                        <h4>Tài khoản của tôi <i class="fa fa-child" aria-hidden="true"></i></h4>
                        <div class="body">
                            <ul class="le-links">
                                <li class="tk-active"><a href="/TaiKhoan">Cập nhật tài khoản</a></li>
                                <li><a href="/TaiKhoan/DoiMatKhau">Mật khẩu</a></li>
                                <li><a href="/TaiKhoan/LichSuDatHang">Lịch sử đặt hàng</a></li>
                            </ul><!-- /.le-links -->
                        </div>
                    </div><!-- /.widget -->
                </aside><!-- /.sidebar .blog-sidebar -->
            </div><!-- /.col -->

            <div class="col-md-9">
                <section class="section register inner-left-xs">
                    <h4 class="text-success">@ViewBag.Success</h4>
                    <br />
                    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "cf-style-1" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)
                        @Html.HiddenFor(model => model.email)
                        @Html.HiddenFor(model => model.password)

                        <div class="field-row">
                            @Html.LabelFor(model => model.email)
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "le-input", @disabled = "true" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="field-row">
                            <label>Họ và tên</label>
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "le-input" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="field-row">
                            <label>Số điện thoại</label>
                            @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "le-input" } })
                            @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="field-row">
                            <label>Địa chỉ</label>
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "le-input" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div><!-- /.field-row -->
                        <div class="buttons-holder">
                            <button type="submit" class="le-button huge">Cập nhật</button>
                        </div><!-- /.buttons-holder -->
                    }
                </section><!-- /.register -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</main><!-- /.inner-bottom-xs -->

DA2.Web/DA2.Web/Views/TaiKhoan/LichSuDatHang.cshtml
@model IEnumerable<DA2.Data.Model.BILL>
@{
    ViewBag.Title = "Lịch sử đặt hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main id="blog" class="inner-bottom-xs">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <aside class="sidebar blog-sidebar">
                    <div class="widget">
                        <h4>Tài khoản của tôi <i class="fa fa-child" aria-hidden="true"></i></h4>
                        <div class="body">
                            <ul class="le-links">
                                <li><a href="/TaiKhoan">Cập nhật tài khoản</a></li>
                                <li><a href="/TaiKhoan/DoiMatKhau">Mật khẩu</a></li>
                                <li class="tk-active"><a href="/TaiKhoan/LichSuDatHang">Lịch sử đặt hàng</a></li>
                            </ul><!-- /.le-links -->
                        </div>
                    </div><!-- /.widget -->
                </aside><!-- /.sidebar .blog-sidebar -->
            </div><!-- /.col -->

            <div class="col-md-9">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Mã hóa đơn</th>
                            <th scope="col">Thời gian mua</th>
                            <th scope="col">Tổng hóa đơn</th>
                            <th scope="col">Người nhận</th>
                            <th scope="col">Tình trạng đơn hàng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>
                                <th scope="row">#@item.id</th>
                                <td>@item.created</td>
                                <td>@item.amount.GetValueOrDefault().ToString("N0")đ</td>
                                <td>@item.nguoi_nhan</td>
                                <td>
                                @if(@item.status == 0)
                                {
                                    <strong class="text-primary">Mới đặt hàng</strong>
                                }
                                else if(@item.status == 1)
                                {
                                    <strong class="text-info">Đã xác nhận</strong>
                                }
                                else if(@item.status == 2)
                                {
                                    <strong class="text-success">Đã giao hàng</strong>
                                }
                                else
                                {
                                    <strong class="text-danger">Hủy đơn hàng</strong>
                                }
                                | <button class="btn btn-info" data-id="@item.id" onclick="showDetails(this)" data-toggle="modal">Xem</button></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</main><!-- /.inner-bottom-xs -->

<div class="modal-xem"></div>

@section js{
    <script>
        function showDetails(clickedElement) {
            var billId = $(clickedElement).attr("data-id");
            showDetailsAjax(billId);
        }

        function showDetailsAjax(billId) {
            var link = '@Url.Action("XemDonHang", "TaiKhoan", new { id = "-1" })'
            link = link.replace("-1", billId);

            $.ajax({
                type: "GET",
                url: link,
                error: function (data)
                { },
                success: function (data) {
                    $('.modal-xem').html(data);
                    $("#detailsModal modal-dialog modal-content .modal-body").html(data);
                    $('#detailsModal').modal('show');
                },
            });
        }
</script>
}

DA2.Web/DA2.Web/Views/TaiKhoan/XemDonHang.cshtml
@model IEnumerable<DA2.Data.Model.BILLITEM>
@{
    var bill = (DA2.Data.Model.BILL)ViewBag.bill;
}
<!-- Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Đơn hàng #@ViewBag.id</h4>
            </div>
            <div class="modal-body">
                <div class="well">
                    <p>Người nhận: <strong>@bill.nguoi_nhan</strong></p>
                    <p>Địa chỉ nhận hàng: <strong>@bill.dia_chi</strong></p>
                    <p>Số điện thoại: <strong>@bill.so_dt</strong></p>
                    <p>Tổng chi phí đơn hàng: <strong>@bill.amount.GetValueOrDefault().ToString("N0")đ</strong></p>
                </div>
                <hr/>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Sản phẩm</th>
                            <th scope="col">Đơn giá</th>
                            <th scope="col">Số lượng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.PRODUCT.name</td>
                                <td>@item.PRODUCT.price.GetValueOrDefault().ToString("N0")đ</td>
                                <td>@item.quantity</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>